---
abstract: "a non-projective dependency natural language\nparser (pure Perl implementation of the MST parser)"
author:
  - 'Rudolf rosa <rosa@ufal.mff.cuni.cz>'
build_requires:
  File::Find: 0
  FindBin: 0
  Test::More: 0
  strict: 0
  utf8: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Treex-Parser-MSTperl
requires:
  Carp: 0
  Data::Dumper: 0
  File::Spec: 0
  File::Temp: 0
  Graph: 0.94
  Graph::ChuLiuEdmonds: 0.05
  Moose: 0
  YAML::Tiny: 0
  autodie: 0
  perl: 5.010
version: 0.11319
